### ISSUE TITLE
Orientation change crashes app

### ISSUE THREAD

**Issue by SharieRhea** [SharieRhea/NY-Eats#1]
The NY Eats app currently crashes upon any orientation change from the device, such as rotating the screen.
Solution: Add support for orientation changes, including new UI layouts for landscape orientations.

**Comment by joeldotdias** [comment]
If this issue is caused due to states being forgotten, consider adding this to your AndroidManifest.xml file in the activity section
```android:configChanges="orientation|screenSize|screenLayout|keyboardHidden"```
